# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2020-01-10 10:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Gateway',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='IpAddress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Prefix',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prefix_name', models.CharField(max_length=100)),
                ('gateway', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='message_routing.Gateway')),
            ],
        ),
        migrations.AddField(
            model_name='gateway',
            name='ip_address',
            field=models.ManyToManyField(to='message_routing.IpAddress'),
        ),
    ]
